### ISSUE TITLE
Wrong amount for invoices with credit note applied to it

### ISSUE THREAD

**Issue by m-hefti** [sinabe/dolibarr-swissqr#13]
The amount indicated on the QR-bill ignores the credit note(s) applied on the bill.

For example, a client get a credit note for any payment exceeding the amount of a previous bill. On the next bill for this client, the credit note is applied and the Due amount is calculated as Bill amount - Credit note = Due amount. This due amount is indicated underneath the Bill amount.

In this case, the QR-code and the amount indicated underneath match the Bill amount, but it should indicate the Due amount.

The bill:
<img width="775" alt="Capture d’écran 2024-02-02 à 18 12 47" src="https://github.com/sinabe/dolibarr-swissqr/assets/68040162/87d9d931-30c2-4eb1-ba90-fdd1ebae1774">

The QR-bill (should display 24.75 and not 126.75)
<img width="421" alt="Capture d’écran 2024-02-02 à 18 13 10" src="https://github.com/sinabe/dolibarr-swissqr/assets/68040162/3fb2eb00-8899-4d48-a2f8-543e2c9bb2b1">

**Comment by m-hefti** [comment]
Any idea how to fix this or when it it will be?

**Comment by benvia** [comment]
Should be fix with the merged PR of today.
