### ISSUE TITLE
Hardcoded Invoice Language

### ISSUE THREAD

**Issue by j1schmid** [sinabe/dolibarr-swissqr#3]
The texts in the invoice, fom example the string "Section paiement" just above the QR-Code, seems to be hardcoded in `htdocs/core/modules/facture/doc/pdf_swissqr.modules.php`.

```
$output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'fr', $pdf);
```

Is there a reasonable way to pass that parameter from Dolibarr? We have just hardcoded the value to our preferred language. For German the patch is:

```
diff --git a/htdocs/core/modules/facture/doc/pdf_swissqr.modules.php b/htdocs/core/modules/facture/doc/pdf_swissqr.modules.php
index cfa572d..8ac6274 100644
--- a/htdocs/core/modules/facture/doc/pdf_swissqr.modules.php
+++ b/htdocs/core/modules/facture/doc/pdf_swissqr.modules.php
@@ -960,7 +960,7 @@ class pdf_swissqr extends ModelePDFFactures
             exit;
         }
 
-        $output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'fr', $pdf);
+        $output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'de', $pdf);
         $output->setPrintable(false)->getPaymentPart();
     }
```

**Comment by benvia** [comment]
Thanks for your feedback.
I will push a new version soon

**Comment by benvia** [comment]
The QR part of the invoice use the same language as the Dolibarr part of the invoice.
Supported languages are German, French, Italian, English
Default language is English
